###1: Subtract a week ( 7 days)Â  from a given date in Python

In [9]:
from datetime import datetime,timedelta
now1 = datetime.now()
print("Today = ", now)
#weekago = datetime(2023, 3, 21, 1, 15)
#print("Week ago - ",weekago)
print("Weekago - ", now - timedelta(weeks = 1))

Today =  2023-03-28 07:47:04.454376
Weekago -  2023-03-21 07:47:04.454376

###2: Add week ( 7 days) and 12 hours to a given date
##Given:
 2020-03-22 10:00:00
given_date = datetime(2020, 3, 22, 10, 0, 0)
Expected output:
2020-03-29 22:00:00

In [10]:
from datetime import datetime,timedelta
now1 = datetime.now()
print("Today = ", now1)
#weekago = datetime(2023, 3, 21, 1, 15)
#print("Week ago - ",weekago)
print("Weekago - ", now1 + timedelta(weeks = 1,hours = 15))

Today =  2023-03-28 07:47:04.454376
Weekago -  2023-04-04 22:47:04.454376

###3: Print ten dates, each two a week apart, starting from today, in the form YYYY-MM-DD.

In [18]:
from datetime import datetime,timedelta
n = datetime.now()
a=0
for i in range(1,11):
  
  x = n + timedelta(weeks = a)
  print(f"{i} Date - ",x.strftime("%Y-%m-%d"))
  a+=2

1 Date -  2023-03-28
2 Date -  2023-04-11
3 Date -  2023-04-25
4 Date -  2023-05-09
5 Date -  2023-05-23
6 Date -  2023-06-06
7 Date -  2023-06-20
8 Date -  2023-07-04
9 Date -  2023-07-18
10 Date -  2023-08-01

###4: Calculate number of days between two given dates
##Given:
 2020-02-25
 
 date_1 = datetime(2020, 2, 25)
 
 2020-09-17

date_2 = datetime(2020, 9, 17)

Expected output:
205 days

In [30]:
import datetime
l1 = list(input("Enter 1st date (YYYY-MM-DD) - ").split("-"))
l2 = list(input("Enter 2nd date (YYYY-MM-DD) - ").split("-"))

x = datetime.datetime(int(l1[0]), int(l1[1]), int(l1[2]))
y = datetime.datetime(int(l1[0]), int(l2[1]), int(l2[2]))
z = x-y
print(z.days," Days")

Enter 1st date (YYYY-MM-DD) - 2022-3-28
Enter 2nd date (YYYY-MM-DD) - 2022-8-28
-153  Days

###5: Write a Python script to display the

a) Current date and time

b) Current year in full

c) Month of year full name

d) Weekday of the week

e) Day of year

f) Day of the month

g) Day of week in full name

In [17]:
from datetime import datetime,timedelta
today = datetime.now()
print("Current date and time - ",today)
print("Current year in full - ",today.strftime("%Y"))
print("Month of year full name - ",today.strftime("%B"))
print("Weekday of the week - ",today.strftime("%A"))
#print("Day of year - ",today.strftime("%j"))
jan1 = datetime(2023,1,1)
print("Day of year - ",today-jan1)
print("Day of month - ",today.strftime("%d"))
print("Day of week - ",today.strftime("%w"))

Current date and time -  2023-03-28 11:33:43.535436
Current year in full -  2023
Month of year full name -  March
Weekday of the week -  Tuesday
Day of year -  86 days, 11:33:43.535436
Day of month -  28
Day of week -  2

###6: Python program to convert a string to datetime:
Jul 1 2016 2:43AM into 2016-07-01 02:43:00

In [10]:
from datetime import datetime
a = input("Enter string of date time - ")
date1 = datetime.strptime(a,"%b %d %Y %I:%M%p")
print(date1)

Enter string of date time - Jul 1 2016 2:43AM
2016-07-01 02:43:00

###7: Python program to convert Year/Month/Day to Day of Year.

In [13]:
from datetime import datetime
a = datetime(2023, 3, 21)
print(a.strftime('%j'))

080